"""create api_key table

Revision ID: 14823256ec61
Revises: 4807ffd6631d
Create Date: 2025-12-23 13:23:35.874153

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "14823256ec61"
down_revision = "4807ffd6631d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
