"""create user table

Revision ID: 4807ffd6631d
Revises: 464413e7c59a
Create Date: 2025-12-23 13:23:13.404700

"""

# revision identifiers, used by Alembic.
revision = "4807ffd6631d"
down_revision = "464413e7c59a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
