"""create api_key table

Revision ID: 855e0444ee82
Revises: 1436e5204292
Create Date: 2025-12-23 13:28:47.127406

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "855e0444ee82"
down_revision = "1436e5204292"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
