"""remove unique from name and phone

Revision ID: e4d5a1f19420
Revises: ac64d564f688
Create Date: 2025-12-22 18:21:28.895170

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e4d5a1f19420"
down_revision = "ac64d564f688"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("borrowers_name_key", "borrowers", type_="unique")
    op.drop_constraint("borrowers_phone_key", "borrowers", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("borrowers_phone_key", "borrowers", ["phone"])
    op.create_unique_constraint("borrowers_name_key", "borrowers", ["name"])
    # ### end Alembic commands ###
